### ISSUE TITLE
Alerts Redesign

### ISSUE THREAD

**Issue by Polarts** [Polarts/sentispace#66]
# Description
The current alerts appear as a part of the page. We want to update them to look more like "snack bar" type of alerts with a stackable design.

# Tasks
- [ ] Create an alerts context that holds an array of alerts, and exposes a `showAlert` method with title, content, and severity arguments.
- [ ] Each 10 seconds the context should automatically pop the topmost alert.
- [ ] Alerts should be displayed like a stack of cards, where the latest is on top.
- [ ] The user should be able to dismiss an alert by swiping it to either side of the screen (use Framer Motion for that).
- [ ] When an alert is dismissed automatically, it plays an animation where it slides to a side.

# Design
## Alerts and their severities
<img src="https://i.imgur.com/S1cBT4E.jpeg">

## Alerts stack
<img src="https://i.imgur.com/rQGm66U.jpeg">

## Alert Positioning
<img src="https://i.imgur.com/pZTDYd5.jpeg">

For precise measurements please refer to the [figma page](https://www.figma.com/file/JC406azeeeGGlTbLAxCs04/Feeling-Tracker?node-id=0%3A1&t=jyrThFgzn0f7LWof-0).

**Comment by Ziv89** [comment]
I will work on it.
