### ISSUE TITLE
(draft) Journal Mode

### ISSUE THREAD

**Issue by Polarts** [Polarts/sentispace#67]
# Description
We're replacing the Day/Week/Month views with Activities/Journal.
The journal view allows the user to write down free text like a diary, rather than creating activities. This aims to expand the target audience and make logging events from your day more accessible.

# Tasks
- [ ] Add a "journal" feature folder with a "journal view" component based on the design, according to the project's folder pattern.
- [ ] Add a `Hashes` enum to represent hash-based routes. The hash routes are `#activities` and `#journal`.
- [ ] Replace the "Change View" button with "Journal" / "Activities" link, based on the design.
- [ ] Render the Activities and Journal views based on the current hash.
